import 'package:festiy/activity.dart';
import 'package:festiy/home.dart';
import 'package:festiy/wallet.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Tickets(),
        ]),
      ),
    );
  }
}

class Tickets extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 83,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 0,
                top: 731,
                child: Container(
                  width: 360,
                  height: 69,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 22,
                top: 746,
                child:GestureDetector(
                onTap: (){
                Navigator.push(context,
                MaterialPageRoute(builder: (context) => Home()),
                );
                },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Home.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 284,
                top: 746,
                child:GestureDetector(
                onTap: (){
                Navigator.push(context,
                MaterialPageRoute(builder: (context) => Wallet()),
                );
                },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Wallet.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 110,
                top: 746,
                child:GestureDetector(
                onTap: (){
                Navigator.push(context,
                MaterialPageRoute(builder: (context) => Tickets()),
                );
                },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Two Tickets.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 310,
                top: 12,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Activity()),
                    );
                  },
                child: Container(
                  width: 50,
                  height: 44,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Menu Vertical.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 200,
                top: 746,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Activity()),
                    );
                  },
                  child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Activity Feed.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
                Positioned(
                left: 28,
                top: 26,
                child: SizedBox(
                  width: 212,
                  height: 44,
                  child: Text(
                    'My Tickets',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 96,
                child: Container(
                  width: 329,
                  height: 70,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 15,
                top: 266,
                child: Container(
                  width: 330,
                  height: 154,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1,
                        top: 84,
                        child: Container(
                          width: 329,
                          height: 70,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 329,
                          height: 70,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 179,
                child: Container(
                  width: 329,
                  height: 70,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 16,
                top: 96,
                child: Container(
                  width: 91,
                  height: 70,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Logo.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 349,
                child: Container(
                  width: 91,
                  height: 70,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Logo.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 266,
                child: Container(
                  width: 91,
                  height: 70,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Logo.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 179,
                child: Container(
                  width: 91,
                  height: 70,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Logo.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 113,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Name',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 146,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Date',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 222,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Date',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 306,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Date',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 391,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Date',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 189,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Name',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 275,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Name',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 367,
                child: SizedBox(
                  width: 77,
                  height: 18,
                  child: Text(
                    'Name',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 259,
                top: 126,
                child: Container(
                  width: 65,
                  height: 20,
                  decoration: ShapeDecoration(
                    color: Color(0x3820F675),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 259,
                top: 211,
                child: Container(
                  width: 65,
                  height: 20,
                  decoration: ShapeDecoration(
                    color: Color(0x3820F676),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 259,
                top: 304,
                child: Container(
                  width: 65,
                  height: 20,
                  decoration: ShapeDecoration(
                    color: Color(0x3820F676),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 259,
                top: 380,
                child: Container(
                  width: 65,
                  height: 20,
                  decoration: ShapeDecoration(
                    color: Color(0x47FF1414),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 270,
                top: 126,
                child: Text(
                  'Active',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Kadwa',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 270,
                top: 211,
                child: Text(
                  'Active',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Kadwa',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 275,
                top: 306,
                child: Text(
                  'Active',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Kadwa',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 266,
                top: 380,
                child: Text(
                  'Cancelled',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 11,
                    fontFamily: 'Kadwa',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}