import 'package:festiy/activity.dart';
import 'package:festiy/home.dart';
import 'package:festiy/tickets.dart';
import 'package:festiy/wallet.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          TransactionsDets(),
        ]),
      ),
    );
  }
}

class TransactionsDets extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 83,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 0,
                top: 731,
                child: Container(
                  width: 360,
                  height: 69,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 22,
                top: 746,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Home()),
                    );
                  },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Home.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 284,
                top: 746,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Wallet()),
                    );
                  },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Wallet.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 110,
                top: 746,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Tickets()),
                    );
                  },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Two Tickets.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 310,
                top: 12,
                child: Container(
                  width: 50,
                  height: 44,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Menu Vertical.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 200,
                top: 746,
                child:GestureDetector(
                  onTap: (){
                    Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Activity()),
                    );
                  },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/Activity Feed.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 62,
                top: 132,
                child: Container(
                  width: 242,
                  height: 376,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 110,
                top: 151,
                child: SizedBox(
                  width: 165,
                  height: 16,
                  child: Text(
                    'Transaction Information',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 178,
                child: Container(
                  width: 112,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE89C9C),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 299,
                child: SizedBox(
                  width: 61,
                  height: 24,
                  child: Text(
                    'From:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 343,
                child: SizedBox(
                  width: 61,
                  height: 24,
                  child: Text(
                    'To:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 388,
                child: SizedBox(
                  width: 61,
                  height: 24,
                  child: Text(
                    'Amount',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 436,
                child: SizedBox(
                  width: 61,
                  height: 21,
                  child: Text(
                    'Time: ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 478,
                child: SizedBox(
                  width: 94,
                  height: 21,
                  child: Text(
                    'Refereal Code',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Kadwa',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 178,
                child: Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/User.png"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}